// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "../interfaces/IZkPorVerifier.sol";

/**
 * @title MockZkVerifier
 * @notice Stub verifier for hackathon demos — always returns true.
 *         In production, swap with a Groth16 / PLONK verifier contract
 *         generated by circom / halo2 / noir.
 */
contract MockZkVerifier is IZkPorVerifier {
    /// @inheritdoc IZkPorVerifier
    function verify(
        bytes calldata /* proof */,
        bytes calldata publicInputs
    ) external pure override returns (bool valid) {
        // Decode and check reserves >= liabilities
        (uint256 reserves, uint256 liabilities, ) =
            abi.decode(publicInputs, (uint256, uint256, bytes32));
        return reserves >= liabilities;
    }
}
