// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/extensions/ERC4626.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";

/**
 * @title MockRWAVault
 * @notice A simple ERC4626 vault that simulates an external RWA yield source
 *         (e.g. tokenised US Treasuries). Used as the target for
 *         RWAAdapterStrategy during hackathon demos.
 *
 * Yield is generated by the owner calling `addYield()` which increases
 * the vault's backing ratio, making each share worth more assets.
 */
contract MockRWAVault is ERC4626 {
    using SafeERC20 for IERC20;

    constructor(
        IERC20 _asset
    ) ERC4626(_asset) ERC20("Mock RWA Vault", "mRWA") {}

    /// @notice Simulate yield accrual by donating assets into the vault.
    ///         Caller must have approved this contract.
    function addYield(uint256 amount) external {
        IERC20(asset()).safeTransferFrom(msg.sender, address(this), amount);
        // Assets increase, shares stay the same → price per share goes up.
    }
}
